openapi: 3.0.0
info:
  title: E-commerce API
  version: 1.0.0
  description: API for managing products, categories, countries, and states in an e-commerce application

servers:
  - url: http://localhost:8080/api

paths:
  /products:
    get:
      summary: Get all products
      description: Retrieve a list of all products
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Page number for pagination
        - in: query
          name: size
          schema:
            type: integer
          description: Number of items per page
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductPage'

  /products/{id}:
    get:
      summary: Get a product by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'

  /product-category:
    get:
      summary: Get all product categories
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductCategory'

  /countries:
    get:
      summary: Get all countries
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Country'

  /states:
    get:
      summary: Get all states
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/State'

  /states/search/findByCountryCode:
    get:
      summary: Get states by country code
      parameters:
        - in: query
          name: code
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/State'

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
        sku:
          type: string
        name:
          type: string
        description:
          type: string
        unitPrice:
          type: number
        imageUrl:
          type: string
        active:
          type: boolean
        unitsInStock:
          type: integer
        dateCreated:
          type: string
          format: date-time
        lastUpdated:
          type: string
          format: date-time
        category:
          $ref: '#/components/schemas/ProductCategory'

    ProductPage:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/Product'
        totalPages:
          type: integer
        totalElements:
          type: integer
        size:
          type: integer
        number:
          type: integer

    ProductCategory:
      type: object
      properties:
        id:
          type: integer
        categoryName:
          type: string

    Country:
      type: object
      properties:
        id:
          type: integer
        code:
          type: string
        name:
          type: string

    State:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        country:
          $ref: '#/components/schemas/Country'