version: 2.1
orbs:
  docker: circleci/docker@1.4.0
workflows:
  docker_build_push:
    jobs:
      - docker/publish:
          context: Docker
          image: victorgrubio/ecommerce-backend-spring
          use-docker-credentials-store: true
