version: 2.1
orbs:
  docker: circleci/docker@1.4.0
workflows:
  lint:
    jobs:
      - docker/hadolint:
          dockerfiles: Dockerfile
  build-push-docker:
    jobs:
      - docker/publish:
          image: victorgrubio/ecommerce-backend-spring
          tag: 'latest,1.0.0'