version: 2.1
orbs:
  docker: circleci/docker@1.4.0
  heroku: circleci/heroku@1.2.2
workflows:
  lint:
    jobs:
      - docker/hadolint:
          dockerfiles: Dockerfile
  build-push-docker:
    jobs:
      - docker/publish:
          image: $DOCKERHUB_REPO
          tag: 'latest, 1.0.0'
  heroku-deployment:
    jobs:
      - heroku/push-docker-image:
          app-name: $HEROKU_APP_NAME