version: 2.1
orbs:
  docker: circleci/docker@1.4.0
workflows:
  build-push-doccker:
    jobs:
      - docker/publish:
          image: victorgrubio/ecommerce-backend-spring
          tags:
            - 'latest,1.0.0'