version: 2.1
orbs:
  docker: circleci/docker@1.4.0
  heroku: circleci/heroku@1.2.2
workflows:
  docker-lint-build-push-heroku:
    jobs:
      - docker/hadolint:
          dockerfiles: Dockerfile
      - docker/publish:
          image: victorgrubio/ecommerce-backend-spring
          tag: 'latest,1.0.0'
      - heroku/push-docker-image:
          context:
            - heroku
          app-name: $HEROKU_APP_NAME