version: 2.1
orbs:
  docker: circleci/docker@1.4.0
  heroku: circleci/heroku@1.2.2
workflows:
  lint:
    jobs:
      - docker/hadolint:
          dockerfiles: Dockerfile
  build-push-heroku-docker:
    jobs:
      - docker/publish:
          image: victorgrubio/ecommerce-backend-spring
          tag: 'latest,1.0.0'
      - heroku-docker-deploy:
          requires:
            - docker/publish

jobs:
  heroku-docker-deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - heroku/install
      - heroku/check-authentication
      - setup_remote_docker
      - checkout
      - heroku/push-docker-image:
          app-name: $HEROKU_APP_NAME
          process-types: "web"
          recursive: true
      - heroku/release-docker-image:
          app-name: HEROKU_APP_NAME
          process-types: web