version: "3.3"
services:
  db:
    image: mysql:8.0.21
    restart: always
    environment:
      MYSQL_DATABASE: "full-stack-ecommerce"
      MYSQL_USER: "ecommerceapp"
      MYSQL_PASSWORD: "ecommerceapp"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3307:3306"
    expose:
      - 3306
    volumes:
      - ./db:/var/lib/mysql